/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get client configuration
         * @description Returns the client bootstrap configuration. Anonymous by design: it tells the SPA whether sign-in is configured and, if so, which Entra client and scope to use. When authentication is not configured the auth property is null and the client skips sign-in.
         */
        get: operations["GetConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my profile
         * @description Returns the signed-in caller's profile, read from the directory on behalf of the caller, including the manager when one is recorded.
         */
        get: operations["GetMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer a question
         * @description Answers a question against the knowledge base and returns the answer text with citations, plus the retrieved chunk texts, which evaluation consumes.
         */
        post: operations["AnswerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create support ticket
         * @description Creates an IT ticket for the signed-in caller and returns it with its number. The caller is taken from the access token, never from the request body.
         */
        post: operations["CreateTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A directory person. */
        Person: {
            /** @description The person's display name. */
            displayName: string;
            /**
             * Format: email
             * @description The person's email address.
             */
            email: string;
        };
        /** @description Entra configuration for the client's sign-in. */
        AuthConfig: {
            /** @description The client application (client) ID. */
            clientId: string;
            /** @description The directory (tenant) ID. */
            tenantId: string;
            /** @description The scope to request for API access. */
            scope: string;
        };
        /** @description Client bootstrap configuration. */
        ClientConfig: {
            /** @description Sign-in configuration, or null when authentication is not configured. */
            auth: components["schemas"]["AuthConfig"] | null;
        };
        /** @description The signed-in caller's profile. */
        UserProfile: {
            /** @description The caller's display name. */
            displayName: string;
            /**
             * Format: email
             * @description The caller's email address.
             */
            email: string;
            /** @description The caller's department, when recorded. */
            department?: string | null;
            /** @description The caller's manager, when one is recorded. */
            manager?: components["schemas"]["Person"] | null;
        };
        /** @description A question for the knowledge base. */
        AnswerRequest: {
            /** @description The question to answer. */
            question: string;
        };
        /** @description A citation backing an answer. */
        Citation: {
            /** @description The cited article's title. */
            title: string;
            /** @description A link to the cited article. */
            url: string;
        };
        /** @description A retrieved knowledge-base chunk. Its text feeds evaluation. */
        RetrievedChunk: {
            /** @description The chunk's article title. */
            title: string;
            /** @description The chunk's text. */
            content: string;
        };
        /** @description An answer with its citations and retrieved chunks. */
        Answer: {
            /** @description The answer text. */
            text: string;
            /** @description The citations backing the answer. */
            citations: components["schemas"]["Citation"][];
            /** @description The retrieved chunks, for evaluation. */
            chunks: components["schemas"]["RetrievedChunk"][];
        };
        /** @description A request to create an IT ticket. */
        CreateTicketRequest: {
            /** @description A one-line summary of the problem. */
            shortDescription: string;
            /** @description A longer description of the problem. */
            description?: string | null;
        };
        /** @description A created IT ticket. */
        Ticket: {
            /** @description The ticket number, on the form IT-yyyyMMdd-XXXX where XXXX is four characters from the Crockford base32 alphabet (pattern ^IT-\d{8}-[0-9A-HJKMNP-TV-Z]{4}$). */
            number: string;
            /** @description A link to the ticket in the ticketing system, when one exists. */
            url?: string | null;
            /** @description The ticket's one-line summary. */
            shortDescription: string;
            caller: components["schemas"]["Person"];
            /**
             * Format: date-time
             * @description When the ticket was created.
             */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The client configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientConfig"];
                };
            };
        };
    };
    GetMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description The request was malformed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnswerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description The answer with citations and retrieved chunks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description The request body was malformed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketRequest"];
            };
        };
        responses: {
            /** @description The ticket was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description The request body was malformed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid access token was presented. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
